name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  fmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Fmt-check
      run: cargo fmt --check

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
    - name: Clippy
      env:
        RUSTFLAGS: "-D warnings"
      run: cargo clippy --verbose --all-features

  
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
    - name: Clippy
      env:
        RUSTFLAGS: "-D warnings"
      run: cargo clippy --verbose --all-features

  
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
    - name: Clippy
      env:
        RUSTFLAGS: "-D warnings"
      run: cargo clippy --verbose --all-features